# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MountainTop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MountainTop
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'NMapsMap'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
end
